title       : Terraform - Azure Examples
description : Curated selection of Terraform code and configuration, for Microsoft Azure.
theme       : jekyll-theme-cayman

navigation:
- text: Home
  url: /
theme: jekyll-theme-midnight